# See https://golangci-lint.run/usage/linters/
version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - funlen
    - gochecknoglobals
    - ireturn
    - nlreturn
    - recvcheck
    - tparallel
    - usetesting
    - wsl
    - funcorder
    - noinlineerr

  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - $gostd
    tagliatelle:
      case:
        rules:
          json: snake
    testifylint:
      disable:
        - go-require
    varnamelen:
      ignore-names:
        - db
        - tt
        - lc
      ignore-decls:
        - sb strings.Builder
        - t testing.T
        - wg sync.WaitGroup
    wrapcheck:
      ignore-package-globs:
        - github.com/patraden/toolkit/pkg/**
        - database/sql
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
