name: Run tests and upload coverage

on: 
  push:
  pull_request:

jobs:
  go:
    name: Go Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Install dependencies
        working-directory: go
        run: go mod download

      - name: Run Go tests with coverage
        working-directory: go
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload Go coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: go/coverage.out
          flags: go
          name: codecov-go
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}